name: 'Deploy to S3 using Docker'
description: 'Deploy the website to an S3 bucket using Docker'

inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the files to deploy'
    required: true

outputs:
  website-url:
    description: 'The URL of the deployed website'

runs:
  using: 'docker'
  image: 'Dockerfile'
